SET FOREIGN_KEY_CHECKS=0;

CREATE DATABASE IF NOT EXISTS sr_db;

USE sr_db;

DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS book;

CREATE TABLE user (
  id BIGINT(10) UNSIGNED AUTO_INCREMENT,
  first_name VARCHAR(45) NOT NULL,
  last_name VARCHAR(45) NOT NULL,
  birth_date DATE NOT NULL,
  password VARCHAR(64) NOT NULL,
  email VARCHAR(60) NOT NULL UNIQUE ,
  phone_number VARCHAR(15) NOT NULL UNIQUE,
  PRIMARY KEY(id)
);

CREATE TABLE book (
  id BIGINT(10) UNSIGNED AUTO_INCREMENT,
  isbn BIGINT(13) UNSIGNED NOT NULL UNIQUE,
  title VARCHAR(200) NOT NULL,
  page_number INT(5),
  price DECIMAL(5, 2) NOT NULL,
  pub_date DATE NOT NULL,
  PRIMARY KEY(id),
  ON DELETE CASCADE
);