SET FOREIGN_KEY_CHECKS=0;

CREATE DATABASE sr_db;

USE sr_db;

DROP TABLE IF EXISTS utente;

CREATE TABLE user (
  id INT(10) UNSIGNED AUTO_INCREMENT,
  first_name VARCHAR(45) NOT NULL,
  last_name VARCHAR(45) NOT NULL,
  birth_date DATE NOT NULL,
  password VARCHAR(64) NOT NULL,
  email VARCHAR(60) NOT NULL UNIQUE ,
  phone_number VARCHAR(15) NOT NULL UNIQUE,
  PRIMARY KEY(id)
);

ALTER TABLE utente AUTO_INCREMENT=1000000007;