version: '3.8'

services:
  db:
    image: mysql
    container_name: sr_db
    restart: no
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql